controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

getSub:
    path: /getsubs
    controller: App\Controller\SubController::index
    methods: GET

addSub:
    path: /addsub
    controller: App\Controller\SubController::addSub
    methods: POST
