controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

getSub:
    path: /getsubs
    controller: App\Controller\SubController::getSubs
    methods: GET

addSub:
    path: /addsub
    controller: App\Controller\SubController::addSub
    methods: POST

listPayTypes:
    path: /payTypes
    methods: GET
    controller: App\Controller\PayController::list

createPayType:
    path: /payType
    methods: POST
    controller: App\Controller\PayController::create

readPayType:
    path: /payType
    methods: GET
    controller: App\Controller\PayController::read

updatePayType:
    path: /payType/{id}
    methods: PUT
    controller: App\Controller\PayController::update

deletePayType:
    path: /payType
    methods: DELETE
    controller: App\Controller\PayController::delete


