controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET



listSubs:
    path: /subs
    methods: GET
    controller: App\Controller\SubController::list

createSub:
    path: /sub
    methods: POST
    controller: App\Controller\SubController::create

updateSub:
    path: /sub/{id}
    methods: PUT
    controller: App\Controller\SubController::update



listPayTypes:
    path: /payTypes
    methods: GET
    controller: App\Controller\PayController::list

createPayType:
    path: /payType
    methods: POST
    controller: App\Controller\PayController::create

readPayType:
    path: /payType
    methods: GET
    controller: App\Controller\PayController::read

updatePayType:
    path: /payType/{id}
    methods: PUT
    controller: App\Controller\PayController::update

deletePayType:
    path: /payType
    methods: DELETE
    controller: App\Controller\PayController::delete


