controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

addindex:
    path: /add
    controller: App\Controller\HomeController::addSub
    methods: POST

